namespace Acode.Domain.Security;

/// <summary>
/// Represents trust boundaries that data crosses in the system.
/// Trust boundary crossings MUST be logged for security audit.
/// Crossing a trust boundary means moving from trusted to untrusted context or vice versa.
/// </summary>
public enum TrustBoundary
{
    /// <summary>
    /// User input boundary - data coming from the user.
    /// Untrusted source requiring validation and sanitization.
    /// Examples: CLI arguments, config file edits, approval responses.
    /// </summary>
    UserInput,

    /// <summary>
    /// LLM output boundary - data generated by language model.
    /// Untrusted source requiring validation before execution.
    /// Examples: Generated code, file modifications, command suggestions.
    /// </summary>
    LlmOutput,

    /// <summary>
    /// File system boundary - data read from or written to disk.
    /// Semi-trusted - repository files trusted, system files untrusted.
    /// Examples: Source code, configuration files, system paths.
    /// </summary>
    FileSystem,

    /// <summary>
    /// Process execution boundary - external process invocation.
    /// Untrusted - process may be compromised or produce malicious output.
    /// Examples: Running tests, build commands, git operations.
    /// </summary>
    ProcessExecution,

    /// <summary>
    /// Network boundary - data sent to or received from network.
    /// Untrusted - network may be compromised or intercepted.
    /// Examples: LLM API calls (if allowed), git remote operations.
    /// </summary>
    Network,

    /// <summary>
    /// Configuration boundary - settings loaded from config files.
    /// Semi-trusted - user controls config, but format validated.
    /// Examples: .agent/config.yml, security policies.
    /// </summary>
    Configuration,

    /// <summary>
    /// Repository boundary - entering or leaving repository scope.
    /// Internal trust zone - repository files generally trusted.
    /// Examples: Accessing files outside repo, symlinks to external paths.
    /// </summary>
    Repository,

    /// <summary>
    /// External dependency boundary - third-party code execution.
    /// Untrusted - dependencies may be compromised.
    /// Examples: NuGet packages, npm modules, Python libraries.
    /// </summary>
    ExternalDependency
}
